package de.nils.conntest.model.event;

public enum EventType
{
    START_CLIENT,
    CLIENT_STARTED,
    STOP_CLIENT,
    CLIENT_STOPPED,
    CLIENT_MESSAGE_RECEIVED,
    CLIENT_MESSAGE_SENT,
    START_SERVER,
    SERVER_STARTED,
    STOP_SERVER,
    SERVER_STOPPED,
    SERVER_MESSAGE_RECEIVED,
    SERVER_MESSAGE_SENT,
    CONNECTION_ESTABLISHED,
    CONNECTION_LOST,
    CONNECTION_RECEIVED_MESSAGE,
    CONNECTION_SENT_MESSAGE,
    START_PORT_SCANNER,
    PORT_SCANNER_FINISHED,
    PORT_SCANNER_RESULT,
	ERROR,
    THEME_CHANGED,
    ENCODING_CHANGED;
}
